
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./NextAuthProvider";
import Header from "@/components/Global/Header";
import GlobalProvider from "@/context/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider >
        <GlobalProvider>
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </GlobalProvider>
      </NextAuthProvider>
    </html>
  );
}
