
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./NextAuthProvider";
import Header from "@/components/Header";
import GlobalProvider, { useGlobalContext } from "@/context/GlobalProvider";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {





  return (
    <html lang="en">
      <GlobalProvider>

        <NextAuthProvider >

          <body className={inter.className}>
            <Header />

            {children}
          </body>
        </NextAuthProvider>
      </GlobalProvider>


    </html>
  );
}
